apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.service.name }}-pv
  labels:
    type: local
spec:
  capacity:
    storage: {{ .Values.mysql.pvc.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mysql   #Directory to mount
    type: DirectoryOrCreate  # Automatically creates the directory if it doesn't exist